version: "3.3"

services:
  main:
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - "5458:5458"
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
    depends_on:
      - postgres
    networks:
      - adminadmin-network

  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #ports:
    #  - "5432:5432"
    networks:
      - adminadmin-network
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/initdb.sql
      - adminadmin-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/public:/usr/share/nginx/html 
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - main
    networks:
      - adminadmin-network

volumes:
  adminadmin-db-data:

networks:
  adminadmin-network:
    driver: bridge
