services:
  main:
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - "5458:5458"
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_ADDR: ${REDIS_ADDR}
      MAIN_LOG_FILE: ${MAIN_LOG_FILE}
      USER_IMAGE_BASE_PATH: ${USER_IMAGE_BASE_PATH}
      RESTAURANT_IMAGE_BASE_PATH: ${RESTAURANT_IMAGE_BASE_PATH}
    volumes:
      - /home/ubuntu/deploy_user/tp_code/:/var/log/
      - /home/ubuntu/deploy_user/tp_code/images_user/:${USER_IMAGE_BASE_PATH}
      - /home/ubuntu/deploy_user/tp_code/images_restaurant/:${RESTAURANT_IMAGE_BASE_PATH}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - adminadmin-network

  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - adminadmin-network
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/initdb.sql
      - adminadmin-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - adminadmin-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  
      - "443:443"
      - "5459:5459"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/deploy_user/tp_code/frontend:/usr/share/nginx/html 
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/ubuntu/deploy_user/tp_code/images_user/:${USER_IMAGE_BASE_PATH}
      - /home/ubuntu/deploy_user/tp_code/images_restaurant/:${RESTAURANT_IMAGE_BASE_PATH}
    depends_on:
      main:
        condition: service_started
    networks:
      - adminadmin-network

volumes:
  redis-data:
  adminadmin-db-data:

networks:
  adminadmin-network:
    driver: bridge
