// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/promocode/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_1_adminadmin/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/satori/uuid"
)

// MockPromocodeRepo is a mock of PromocodeRepo interface.
type MockPromocodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeRepoMockRecorder
}

// MockPromocodeRepoMockRecorder is the mock recorder for MockPromocodeRepo.
type MockPromocodeRepoMockRecorder struct {
	mock *MockPromocodeRepo
}

// NewMockPromocodeRepo creates a new mock instance.
func NewMockPromocodeRepo(ctrl *gomock.Controller) *MockPromocodeRepo {
	mock := &MockPromocodeRepo{ctrl: ctrl}
	mock.recorder = &MockPromocodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeRepo) EXPECT() *MockPromocodeRepoMockRecorder {
	return m.recorder
}

// GetDiscount mocks base method.
func (m *MockPromocodeRepo) GetDiscount(ctx context.Context, user_id uuid.UUID, promocode string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscount", ctx, user_id, promocode)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscount indicates an expected call of GetDiscount.
func (mr *MockPromocodeRepoMockRecorder) GetDiscount(ctx, user_id, promocode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscount", reflect.TypeOf((*MockPromocodeRepo)(nil).GetDiscount), ctx, user_id, promocode)
}

// GetPromocodes mocks base method.
func (m *MockPromocodeRepo) GetPromocodes(ctx context.Context, user_id uuid.UUID, count, offset int) ([]models.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromocodes", ctx, user_id, count, offset)
	ret0, _ := ret[0].([]models.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromocodes indicates an expected call of GetPromocodes.
func (mr *MockPromocodeRepoMockRecorder) GetPromocodes(ctx, user_id, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromocodes", reflect.TypeOf((*MockPromocodeRepo)(nil).GetPromocodes), ctx, user_id, count, offset)
}

// MockPromocodeUsecase is a mock of PromocodeUsecase interface.
type MockPromocodeUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeUsecaseMockRecorder
}

// MockPromocodeUsecaseMockRecorder is the mock recorder for MockPromocodeUsecase.
type MockPromocodeUsecaseMockRecorder struct {
	mock *MockPromocodeUsecase
}

// NewMockPromocodeUsecase creates a new mock instance.
func NewMockPromocodeUsecase(ctrl *gomock.Controller) *MockPromocodeUsecase {
	mock := &MockPromocodeUsecase{ctrl: ctrl}
	mock.recorder = &MockPromocodeUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeUsecase) EXPECT() *MockPromocodeUsecaseMockRecorder {
	return m.recorder
}

// CheckPromocode mocks base method.
func (m *MockPromocodeUsecase) CheckPromocode(ctx context.Context, user_id uuid.UUID, promocode string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPromocode", ctx, user_id, promocode)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPromocode indicates an expected call of CheckPromocode.
func (mr *MockPromocodeUsecaseMockRecorder) CheckPromocode(ctx, user_id, promocode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPromocode", reflect.TypeOf((*MockPromocodeUsecase)(nil).CheckPromocode), ctx, user_id, promocode)
}

// GetPromocodes mocks base method.
func (m *MockPromocodeUsecase) GetPromocodes(ctx context.Context, user_id uuid.UUID, count, offset int) ([]models.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromocodes", ctx, user_id, count, offset)
	ret0, _ := ret[0].([]models.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromocodes indicates an expected call of GetPromocodes.
func (mr *MockPromocodeUsecaseMockRecorder) GetPromocodes(ctx, user_id, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromocodes", reflect.TypeOf((*MockPromocodeUsecase)(nil).GetPromocodes), ctx, user_id, count, offset)
}
