// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/restaurants/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_1_adminadmin/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/satori/uuid"
)

// MockRestaurantRepo is a mock of RestaurantRepo interface.
type MockRestaurantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantRepoMockRecorder
}

// MockRestaurantRepoMockRecorder is the mock recorder for MockRestaurantRepo.
type MockRestaurantRepoMockRecorder struct {
	mock *MockRestaurantRepo
}

// NewMockRestaurantRepo creates a new mock instance.
func NewMockRestaurantRepo(ctrl *gomock.Controller) *MockRestaurantRepo {
	mock := &MockRestaurantRepo{ctrl: ctrl}
	mock.recorder = &MockRestaurantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantRepo) EXPECT() *MockRestaurantRepoMockRecorder {
	return m.recorder
}

// CreateReviews mocks base method.
func (m *MockRestaurantRepo) CreateReviews(ctx context.Context, req models.Review, id, restaurantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviews", ctx, req, id, restaurantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReviews indicates an expected call of CreateReviews.
func (mr *MockRestaurantRepoMockRecorder) CreateReviews(ctx, req, id, restaurantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviews", reflect.TypeOf((*MockRestaurantRepo)(nil).CreateReviews), ctx, req, id, restaurantID)
}

// GetAll mocks base method.
func (m *MockRestaurantRepo) GetAll(ctx context.Context, count, offset int) ([]models.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, count, offset)
	ret0, _ := ret[0].([]models.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRestaurantRepoMockRecorder) GetAll(ctx, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRestaurantRepo)(nil).GetAll), ctx, count, offset)
}

// GetProductsByRestaurant mocks base method.
func (m *MockRestaurantRepo) GetProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID, count, offset int) (*models.RestaurantFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByRestaurant", ctx, restaurantID, count, offset)
	ret0, _ := ret[0].(*models.RestaurantFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByRestaurant indicates an expected call of GetProductsByRestaurant.
func (mr *MockRestaurantRepoMockRecorder) GetProductsByRestaurant(ctx, restaurantID, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByRestaurant", reflect.TypeOf((*MockRestaurantRepo)(nil).GetProductsByRestaurant), ctx, restaurantID, count, offset)
}

// GetReviews mocks base method.
func (m *MockRestaurantRepo) GetReviews(ctx context.Context, restaurantID uuid.UUID, count, offset int) ([]models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviews", ctx, restaurantID, count, offset)
	ret0, _ := ret[0].([]models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviews indicates an expected call of GetReviews.
func (mr *MockRestaurantRepoMockRecorder) GetReviews(ctx, restaurantID, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviews", reflect.TypeOf((*MockRestaurantRepo)(nil).GetReviews), ctx, restaurantID, count, offset)
}

// ReviewExists mocks base method.
func (m *MockRestaurantRepo) ReviewExists(ctx context.Context, userID, restaurantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewExists", ctx, userID, restaurantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewExists indicates an expected call of ReviewExists.
func (mr *MockRestaurantRepoMockRecorder) ReviewExists(ctx, userID, restaurantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewExists", reflect.TypeOf((*MockRestaurantRepo)(nil).ReviewExists), ctx, userID, restaurantID)
}

// MockRestaurantUsecase is a mock of RestaurantUsecase interface.
type MockRestaurantUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantUsecaseMockRecorder
}

// MockRestaurantUsecaseMockRecorder is the mock recorder for MockRestaurantUsecase.
type MockRestaurantUsecaseMockRecorder struct {
	mock *MockRestaurantUsecase
}

// NewMockRestaurantUsecase creates a new mock instance.
func NewMockRestaurantUsecase(ctrl *gomock.Controller) *MockRestaurantUsecase {
	mock := &MockRestaurantUsecase{ctrl: ctrl}
	mock.recorder = &MockRestaurantUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantUsecase) EXPECT() *MockRestaurantUsecaseMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockRestaurantUsecase) CreateReview(ctx context.Context, req models.ReviewInReq, id, restaurantID uuid.UUID, login string) (models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", ctx, req, id, restaurantID, login)
	ret0, _ := ret[0].(models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockRestaurantUsecaseMockRecorder) CreateReview(ctx, req, id, restaurantID, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockRestaurantUsecase)(nil).CreateReview), ctx, req, id, restaurantID, login)
}

// GetAll mocks base method.
func (m *MockRestaurantUsecase) GetAll(ctx context.Context, count, offset int) ([]models.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, count, offset)
	ret0, _ := ret[0].([]models.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRestaurantUsecaseMockRecorder) GetAll(ctx, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRestaurantUsecase)(nil).GetAll), ctx, count, offset)
}

// GetProductsByRestaurant mocks base method.
func (m *MockRestaurantUsecase) GetProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID, count, offset int) (*models.RestaurantFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByRestaurant", ctx, restaurantID, count, offset)
	ret0, _ := ret[0].(*models.RestaurantFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByRestaurant indicates an expected call of GetProductsByRestaurant.
func (mr *MockRestaurantUsecaseMockRecorder) GetProductsByRestaurant(ctx, restaurantID, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByRestaurant", reflect.TypeOf((*MockRestaurantUsecase)(nil).GetProductsByRestaurant), ctx, restaurantID, count, offset)
}

// GetReviews mocks base method.
func (m *MockRestaurantUsecase) GetReviews(ctx context.Context, restaurantID uuid.UUID, count, offset int) ([]models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviews", ctx, restaurantID, count, offset)
	ret0, _ := ret[0].([]models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviews indicates an expected call of GetReviews.
func (mr *MockRestaurantUsecaseMockRecorder) GetReviews(ctx, restaurantID, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviews", reflect.TypeOf((*MockRestaurantUsecase)(nil).GetReviews), ctx, restaurantID, count, offset)
}

// ReviewExists mocks base method.
func (m *MockRestaurantUsecase) ReviewExists(ctx context.Context, userID, restaurantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewExists", ctx, userID, restaurantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewExists indicates an expected call of ReviewExists.
func (mr *MockRestaurantUsecaseMockRecorder) ReviewExists(ctx, userID, restaurantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewExists", reflect.TypeOf((*MockRestaurantUsecase)(nil).ReviewExists), ctx, userID, restaurantID)
}
