name: Deploy Backend

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy_user/tp_code/2025_1_adminadmin
            sudo docker-compose down || exit 1
            sudo git pull || exit 1
            sudo docker-compose build || exit 1
            sudo docker-compose up -d || exit 1
            sleep 10
            sudo docker ps || exit 1
            sudo docker logs $(sudo docker ps -q --filter "ancestor=nginx") || exit 1
