name: Deploy Backend

on:
  push:
    branches:
      - dev
      - main 

jobs:
  adminadmin-tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Run test with cover
        run:
          sudo apt-get install libwebp-dev
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  build:
    needs: adminadmin-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              sudo chown -R ubuntu:ubuntu /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              git config --global --add safe.directory /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              cd /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              sudo docker compose down nginx main auth cart redis postgres || exit 1
              git checkout ${{ github.ref_name }} || exit 1
              sudo git pull || exit 1
              sudo docker compose build || exit 1
              sudo docker compose up -d || exit 1