name: Deploy Backend

on:
  push:
    branches:
      - dev
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              sudo chown -R ubuntu:ubuntu /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              git config --global --add safe.directory /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              cd /home/ubuntu/deploy_user/tp_code/2025_1_adminadmin
              sudo docker compose down nginx main auth cart redis postgres|| exit 1
              git checkout ${{ github.ref_name }} || exit 1
              sudo git pull || exit 1
              sudo docker compose build || exit 1
              sudo docker compose up -d || exit 1